// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rjbdcucejlsegbgqmoao.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqYmRjdWNlamxzZWdiZ3Ftb2FvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk0MTM4MzQsImV4cCI6MjA3NDk4OTgzNH0.c-lq7oQpCbLxTkbm-1yioocqw_QD_YakOnM8vp1JAaU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});